name: CI

on:
  pull_request:
    branches:
      - dev
      - master
    paths-ignore:
      - ".github/**"
      - "**.md"
    types: [opened, reopened, synchronize]
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - ".github/**"
      - "**.md"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: "1.24.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: "1.24.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  build:
    needs: [lint, test]
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: "1.24.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./cmd/note-nest/...
